app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/breadwallet/BreadApp.java
app/src/main/java/com/breadwallet/presenter/fragments/FragmentSend.kt
app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java
app/src/main/java/com/breadwallet/tools/manager/BRNotificationManager.java
app/src/main/java/com/breadwallet/tools/manager/SyncManager.java

There was a major issue with a server and it caused major outages for people.
- There was a bug in the software that caused the send fucntion to be stuck (returned before gettting a fee value)
- Fixed some other minor issues
- Upgraded the FIrebase dep

💣🐞[Hotbug fix] sharedprefs fb fix

---

.circleci/config.yml

First effort to get CircleCI working
#Closes 
#73

🚧[Techdebt] Add .circleci/config.yml

---

app/build.gradle
app/src/main/java/com/breadwallet/presenter/activities/settings/AboutActivity.java
app/src/main/java/com/breadwallet/presenter/fragments/DynamicDonationFragment.java
app/src/main/java/com/breadwallet/tools/util/BRConstants.java
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/bread_alert_dialog.xml
app/src/main/res/layout/fragment_dynamic_donation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-in/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/android_strings.xml
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Feature - donation disclaimer modal

---

app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java

- reduce emissions of "java.lang.IllegalArgumentException: Unsupported ISO 3166 country: en" being sent to crashlytics

Task - Reduce country iso exception

---

app/src/main/java/com/breadwallet/ui/card/CardFragment.kt

The next step post v2.8.0 is to add more javascript functionality. This should be out of functional scope so callbacks are registered.
This is just a baby step to make sure it makes sense

🦺[Techdebt] Make webview var

---

app/build.gradle
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-in/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/android_strings.xml
app/src/main/res/values/strings.xml

Went through the strings.xml files and removes unused entries.

🐜[Bugfix] Refactor strings files

---

app/build.gradle
app/src/main/java/com/breadwallet/presenter/activities/LoginActivity.java
app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
app/src/main/java/com/breadwallet/presenter/activities/settings/AboutActivity.java
app/src/main/java/com/breadwallet/presenter/fragments/FragmentBuy.java
app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java
app/src/main/java/com/breadwallet/tools/manager/BREventManager.java
app/src/main/java/com/breadwallet/tools/util/BRConstants.java
app/src/main/java/com/breadwallet/ui/card/CardFragment.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-in/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/android_strings.xml
app/src/main/res/values/strings.xml

- 🐜[Bugfix] Refactor strings files (#122)
- Refactors version name and code to BRConstants (#121)
- Task - Reduce country iso exception (#118)
- reduce emissions of "java.lang.IllegalArgumentException: Unsupported ISO 3166 country: en"
- Feature - Show Litecoin Card as Webview (#82)
- Feature - donation disclaimer modal (#75)

🚀[Release v.2.8.0] Merge into Develop

---

app/build.gradle
app/src/main/java/com/breadwallet/presenter/fragments/FragmentBuy.java

- 🦟[Bug Report] Crashlytics: FragmentFingerprint.java line 256
- 🦟[Bug Report] Crashlytics: DisplayListCanvas.java line 229

🚀[ Release v.2.8.1] Merge into Develop

---

app/build.gradle
app/src/main/java/com/breadwallet/tools/util/BRConstants.java
app/src/main/java/com/breadwallet/wallet/BRPeerManager.java

This is the last major release prior to work on Newborn, the refactored Litewallet Android. While there are many requests to improve the current codebase, it is actually 7 years of patching and rework and the cost / time of maintenance is no longer worth it.
We looked at the most important features needed and addressed them in this release.
They are:
- Bech32 support for sending to `1ltc` addresses
- Allow user to see their 12 words / seed phrase
- User preferences for sync vs anonymity (false positives rate)

🚀[ Release v.2.8.4] Merge into Develop

---

app/build.gradle
app/src/main/java/com/breadwallet/BreadApp.java
app/src/main/java/com/breadwallet/tools/util/Utils.java
fast_follow_asset_pack_01/build.gradle
install_time_asset_pack/build.gradle
settings.gradle

Able to get the project to compile
- Added PAD (Play Asset Delivery)

[Tech Debt] Normalized working version

---

app/src/main/java/com/breadwallet/entities/IntroLanguage.kt
app/src/main/java/com/breadwallet/entities/IntroLanguageResource.kt
app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
app/src/main/java/com/breadwallet/tools/adapter/CountryLanguageAdapter.kt
app/src/main/java/com/breadwallet/tools/adapter/TransactionListAdapter.java
app/src/main/java/com/breadwallet/tools/manager/SyncManager.java
app/src/main/res/layout/syncing_item.xml

Hello!
What's for?
This PR is to add functionality to the button yes language in IntroActivity.

Added Functionality to button yes language

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/breadwallet/BreadApp.java
app/src/main/java/com/breadwallet/tools/util/PushNotificationService.kt

Hello! This is for setting up FCM Push Notifications to our app.
Note: for api 13 and above, user needs to allows notifications permission to receive our notifications with FCM Push Notifications.
Here is the test on emulator:
Where to send the notifications? We can send it through google firebase console -> messaging -> add new campaign -> choose notifications

Added FCM Push Notifications

---

app/build.gradle

Updated target API to level 14 (SDK Version 34).

Updated target API to level 14 (SDK Version 34)

---

app/build.gradle
app/src/androidTest/java/com/breadwallet/analytics/AnalyticsTests.java
app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
app/src/main/java/com/breadwallet/tools/util/BRConstants.java

- Removed the Ternio event code
- Added new Analytics events

Update review blogic

---

app/src/main/java/com/breadwallet/BreadApp.java
app/src/main/java/com/breadwallet/presenter/entities/PartnerNames.kt
app/src/main/java/com/breadwallet/tools/util/Utils.java

Adding analytics package to more accurately track installs

Tech debt/add af sdk

---

app/build.gradle
app/evil.json
app/src/canary-file.json
app/src/main/java/com/breadwallet/BreadApp.java
app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
app/src/main/java/com/breadwallet/tools/adapter/TransactionListAdapter.java
app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java
app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
app/src/main/java/com/breadwallet/tools/manager/SyncManager.java
app/src/main/java/com/breadwallet/tools/manager/TxManager.java
app/src/main/java/com/breadwallet/tools/util/Utils.java
app/src/main/java/com/breadwallet/wallet/BRPeerManager.java
app/src/main/java/com/breadwallet/wallet/BRWalletManager.java
app/src/main/java/com/platform/APIClient.java
app/src/main/java/com/platform/tools/KVStoreManager.java
install_time_asset_pack/src/main/assets/canary-file.json

Debugged the install issue with send
- Moved all the measurements in new methods
- recalculated measure points
- Added analytics
- event did_complete_sync was shown!
- adding a dummy file to make sure file system is set
||||WIP still verifying the JSON is present
- added a blockheight label
-  changed the sleep time (a hack to allow the device time to refresh the view) to 100 ms from 500ms!!
-WIP Why is the bundle not showing on time

Techdebt/ fixed send issue add syncing measurements

---

app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java
app/src/main/java/com/breadwallet/presenter/fragments/FragmentPin.java
app/src/main/java/com/breadwallet/tools/animation/BRAnimator.java
app/src/main/java/com/breadwallet/tools/security/AuthManager.java
app/src/main/java/com/breadwallet/tools/security/BRSender.java

- Change `android.app.Activity` to `androidx.fragment.app.FragmentActivity`
- Change `android.app.Fragment` to `androidx.fragment.app.Fragment`
- Change `getFragmentManager` to `getSupportFragmentManager ` from androidx
- add new logic `!app.getSupportFragmentManager().isStateSaved()` to `killAllFragments`

fix: [#152] make sure using Fragment, FragmentManager and more

---

app/src/main/java/com/breadwallet/tools/security/BRKeyStore.java

* Add null checking for `BRKeyStore.removeAliasAndFiles`

fix: [#264] add null checking for BRKeyStore.removeAliasAndFiles

---

app/src/main/java/com/breadwallet/tools/security/BRKeyStore.java

Simplify exception handling at BRKeyStore._getData and record exception to Firebase Crashlytics. 
Now only 2 `catch`
* `UserNotAuthenticatedException`, this class inherit from `InvalidKeyException` 
* `GeneralSecurityException | IOException e`
*  `GeneralSecurityException` this class is parent of 
* `CertificateException`
* `KeyStoreException`
* `UnrecoverableKeyException`
* `NoSuchAlgorithmException `
* `NoSuchPaddingException`
* `InvalidAlgorithmParameterException`
* `IOException`
We are recording the non-fatal exception using [this](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts), so we can monitor the error from Crashlytics

chore: [#126] simplify exception handling at BRKeyStore._getData and record exception to Firebase Crashlytics

---

app/build.gradle
app/src/main/java/com/breadwallet/presenter/fragments/FragmentTransactionItem.java

Hello! This pr added abilities to copy transaction id to clipboard by click it.

Added abilities to copy transaction id by click the transaction id

---

app/build.gradle

Switching gears from fire fighting to better maintaining the codebase. 
More config and code improvements.
Play Store Approved

🚀[Release v2.13.0] Merge into Develop

---

app/src/test/java/com/litewallet/tools/util/BRConstantsTest.kt

Hello! This pr is for added test BRConstants MockK + JUnit4.
Test results:

Added tests BRConstants MockK+JUnit4

---

app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
app/src/main/java/com/breadwallet/presenter/activities/settings/DisplayCurrencyActivity.java
app/src/main/res/layout/activity_display_currency.xml

fix user unable to set preferred local fiat currency and fix close button at `activity_display_currency`
https://github.com/litecoin-foundation/litewallet-engineering/issues/11

fix: fix User unable to set preferred local fiat currency
